version: "3"

volumes:
  database:
    driver: local

services:
  postgres:
    platform: linux/amd64
    image: postgres:latest
    container_name: turborepo_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - database:/var/lib/postgres
